@host=https://localhost:7122

POST {{host}}/authentication/register
Content-Type: application/json

{
    "firstName": "Tajma",
    "lastName": "Heinz",
    "email": "t.heinz@example.com",
    "password": "Pwd12345."
}