@host=https://localhost:5001

POST {{host}}/authentication/register
Content-Type: application/json

{
    "firstName": "Tajma",
    "lastName": "Heinz",
    "email": "t.heinz@contoso.com",
    "password": "Pwd12345."
}