@host=https://localhost:7122

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImN0eSI6IkpXVCJ9.eyJzdWIiOiIzODBiNmYyOC1mNzQzLTRiYjctOGExYS04MGI2NjY0ZDA3NTIiLCJnaXZlbl9uYW1lIjoiVGFqbWEiLCJmYW1pbHlfbmFtZSI6IkhlaW56IiwianRpIjoiZTc3NjFlZjEtOGNmMy00YjViLTlhZjYtZDQ5OGIwMThkYmQwIiwiZXhwIjoxNjYxMzM2MTY0LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.Hdctc8HsOOJB7oFYrDXrQy2G3wsBOZKLcCPD5Olk1fY